language: elixir

sudo: false

elixir:
  - 1.8
  - 1.7

otp_release:
  - 19.0
  - 20.0
  - 21.0

script:
  - mix test
  - mix format --check-formatted

# after_script:
#   - mix deps.get --only docs
#   - MIX_ENV=docs mix inch.report